language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - "pip install pytest pytest-cov nose"
  - "pip install coveralls"
  - "pip install -e ."
script: 
  - py.test --cov affine --cov-report term-missing
after_success:
  - coveralls
