sudo: false
language: python
cache: pip
python:
  - 2.7
  - 3.6
install:
  - pip install wheel
  - pip install .[test]
script:
  - pytest --cov affine --cov-report term-missing
after_success:
  - pip install coveralls
  - coveralls
deploy:
  on:
    tags: true
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: seang
