language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - "pip install pytest"
  - "pip install coveralls"
  - "pip install -e ."
script: 
  - py.test
  - coverage run --source=rasterio --omit='*.pxd,*.pyx,*/tests/*,*/docs/*,*/examples/*,*/benchmarks/*' -m py.test
after_success:
  - coveralls
