sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install pytest pytest-cov nose"
  - "pip install coveralls"
  - "pip install -e ."
script: 
  - python -m pytest affine/tests --cov affine --cov-report term-missing
after_success:
  - coveralls
deploy:
  on:
    tags: true
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: seang
